import { parseEnterpriseUrl, type Credentials } from './api'

const ENT_SLUG = /^[A-Za-z0-9._-]+$/
const ENT_HOST = /^(github\.com|[a-z0-9-]+\.ghe\.com)$/
const HOST_PATH_FORM = /^([^/]+)\/enterprises\/([^/]+)(?:\/.*)?$/

/**
 * Optional `?ent=...` query param that prefills the Enterprise URL field
 * in the connect form. Accepts:
 *
 *   - a bare slug (`?ent=acme`) → normalized to
 *     `https://github.com/enterprises/acme`, or
 *   - a scheme-less enterprise URL
 *     (`?ent=acme.ghe.com/enterprises/acme-corp`) → normalized to
 *     `https://acme.ghe.com/enterprises/acme-corp`. GHE.com tenants
 *     share their pre-fill link in this form, which is just the
 *     browser address bar URL with `https://` stripped off.
 *
 * A full URL (`?ent=https://acme.ghe.com/enterprises/acme`) is also
 * accepted as a silent legacy fallback so links generated by older
 * builds keep working.
 *
 * Invalid values (garbage, unparseable URLs, slugs with disallowed
 * characters, non-GitHub hosts) return `null` so the caller can fall
 * back to its default.
 *
 * Note: only the URL is read from query params. The PAT is always
 * entered manually to avoid leakage via history, referrer, or server
 * logs.
 */
export function readEnterpriseUrlFromUrl(): string | null {
  if (typeof window === 'undefined') return null
  const params = new URLSearchParams(window.location.search)
  const raw = params.get('ent')
  if (!raw) return null
  const trimmed = raw.trim()
  if (!trimmed) return null

  // Legacy full-URL form. Re-parse host and slug out of the URL so we
  // can apply the same allowlist as the short form. Accepts URLs with
  // extra path segments after the slug (e.g. `/enterprises/foo/settings`)
  // so links copied from an admin's browser address bar still work.
  if (/^https?:\/\//i.test(trimmed)) {
    let u: URL
    try {
      u = new URL(trimmed)
    } catch {
      return null
    }
    const m = u.pathname.match(/^\/enterprises\/([^/]+)/)
    if (!m) return null
    return buildEnterpriseUrl(u.host, m[1])
  }

  // Scheme-less enterprise URL: `<host>/enterprises/<slug>`. Tolerates
  // trailing path segments the same way the legacy branch does.
  const hostPath = trimmed.match(HOST_PATH_FORM)
  if (hostPath) return buildEnterpriseUrl(hostPath[1], hostPath[2])

  // Bare slug. github.com is implied; anything with a slash that did
  // not match the patterns above is rejected.
  if (trimmed.includes('/')) return null
  return buildEnterpriseUrl('github.com', trimmed)
}

function buildEnterpriseUrl(host: string, slug: string): string | null {
  const normalizedHost = host.toLowerCase()
  if (!ENT_HOST.test(normalizedHost)) return null
  if (!ENT_SLUG.test(slug)) return null
  const candidate = `https://${normalizedHost}/enterprises/${slug}`
  return parseEnterpriseUrl(candidate) ? candidate : null
}

/**
 * Build a shareable link that pre-fills the Enterprise URL on the
 * connect form. Returns `null` for demo credentials (nothing real to
 * share) or when the API base can't be parsed.
 *
 * github.com tenants get the short `?ent=<slug>` form; GHE.com tenants
 * get `?ent=<host>/enterprises/<slug>`, which mirrors the address-bar
 * URL minus the scheme. Both forms use characters that are safe in a
 * URL query value, so no percent-encoding is applied and the link
 * stays readable when shared in chat or email.
 */
export function buildShareableEnterpriseUrl(
  credentials: Credentials,
  origin: string,
  pathname: string,
): string | null {
  if (credentials.base === 'demo://') return null
  let host: string
  try {
    host = new URL(credentials.base).host
  } catch {
    return null
  }
  // API bases are `api.<webhost>`; strip the prefix to recover the
  // user-facing host (`github.com` or `<tenant>.ghe.com`).
  const webHost = host.startsWith('api.') ? host.slice(4) : host
  // Round-trip property: the builder never emits a value the reader
  // would reject. If a connected enterprise carries chars outside the
  // safe set (unexpected in practice, since the API only ever returns
  // GitHub-issued slugs), fall back to null instead of producing a
  // malformed link.
  if (!ENT_HOST.test(webHost)) return null
  if (!ENT_SLUG.test(credentials.ent)) return null
  const entValue =
    webHost === 'github.com'
      ? credentials.ent
      : `${webHost}/enterprises/${credentials.ent}`
  return `${origin}${pathname}?ent=${entValue}`
}
